### ISSUE TITLE
Page Up / Page Down und Shift Tab

### ISSUE THREAD

**Issue by MarioLung** [skrysmanski/windows-pc-keyboard-layout-mac#1]
Hallo,
es funktioniert alles super aber Leider Fehle mir folgende Tasten noch

Page Up (Bild Rauf) für Seiten Anfang)
Page Down (Bild Runter für Seiten Ende)
Shift + TAB (entfernt die vorherigen Tab)

ich wollte das schon selber machen
aber in ukelele werden nicht alle Tasten angezeigt

Danke
Mario

**Comment by skrysmanski** [comment]
Hallo Mario,

> Page Up (Bild Rauf) für Seiten Anfang)
> Page Down (Bild Runter für Seiten Ende)

PageUp ist Fn+Up - PageDown ist Fn+Down

> Shift + TAB (entfernt die vorherigen Tab)

Was genau funktioniert hier nicht?
